import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import StoreProvider from '@/lib/providers/StoreProvider';
import PlaybackBar from '@/components/playback-bar';
import AudioPlayer from '@/components/AudioPlayer';
import AuthProvider from '@/lib/providers/AuthProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <StoreProvider>
            <div className="bg-background relative min-h-screen">
              {/* Background gradients */}
              <div className="from-background via-background-light/10 to-primary/5 absolute inset-0 bg-gradient-to-br" />
              <div className="from-primary/10 via-background to-background absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))]" />

              {/* Content */}
              <div className="relative">
                <Navbar />
                {children}
                <PlaybackBar />
                <AudioPlayer />
              </div>
            </div>
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
